/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FilesIndexImport } from './routes/files/index'
import { Route as LayersLayerIdImport } from './routes/layers/$layerId'
import { Route as EntitiesEntityIdImport } from './routes/entities/$entityId'
import { Route as BlocksBlockIdImport } from './routes/blocks/$blockId'
import { Route as FilesFileIdIndexImport } from './routes/files/$fileId/index'
import { Route as FilesFileIdPatLessComponentsRouteImport } from './routes/files/$fileId/_patLessComponents/route'
import { Route as FilesFileIdPatLessComponentsLayersImport } from './routes/files/$fileId/_patLessComponents/layers'
import { Route as FilesFileIdPatLessComponentsBlocksImport } from './routes/files/$fileId/_patLessComponents/blocks'

// Create Virtual Routes

const FilesFileIdImport = createFileRoute('/files/$fileId')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FilesFileIdRoute = FilesFileIdImport.update({
  id: '/files/$fileId',
  path: '/files/$fileId',
  getParentRoute: () => rootRoute,
} as any)

const FilesIndexRoute = FilesIndexImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRoute,
} as any)

const LayersLayerIdRoute = LayersLayerIdImport.update({
  id: '/layers/$layerId',
  path: '/layers/$layerId',
  getParentRoute: () => rootRoute,
} as any)

const EntitiesEntityIdRoute = EntitiesEntityIdImport.update({
  id: '/entities/$entityId',
  path: '/entities/$entityId',
  getParentRoute: () => rootRoute,
} as any)

const BlocksBlockIdRoute = BlocksBlockIdImport.update({
  id: '/blocks/$blockId',
  path: '/blocks/$blockId',
  getParentRoute: () => rootRoute,
} as any)

const FilesFileIdIndexRoute = FilesFileIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilesFileIdRoute,
} as any)

const FilesFileIdPatLessComponentsRouteRoute =
  FilesFileIdPatLessComponentsRouteImport.update({
    id: '/_patLessComponents',
    getParentRoute: () => FilesFileIdRoute,
  } as any)

const FilesFileIdPatLessComponentsLayersRoute =
  FilesFileIdPatLessComponentsLayersImport.update({
    id: '/layers',
    path: '/layers',
    getParentRoute: () => FilesFileIdPatLessComponentsRouteRoute,
  } as any)

const FilesFileIdPatLessComponentsBlocksRoute =
  FilesFileIdPatLessComponentsBlocksImport.update({
    id: '/blocks',
    path: '/blocks',
    getParentRoute: () => FilesFileIdPatLessComponentsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blocks/$blockId': {
      id: '/blocks/$blockId'
      path: '/blocks/$blockId'
      fullPath: '/blocks/$blockId'
      preLoaderRoute: typeof BlocksBlockIdImport
      parentRoute: typeof rootRoute
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdImport
      parentRoute: typeof rootRoute
    }
    '/layers/$layerId': {
      id: '/layers/$layerId'
      path: '/layers/$layerId'
      fullPath: '/layers/$layerId'
      preLoaderRoute: typeof LayersLayerIdImport
      parentRoute: typeof rootRoute
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesIndexImport
      parentRoute: typeof rootRoute
    }
    '/files/$fileId': {
      id: '/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdImport
      parentRoute: typeof rootRoute
    }
    '/files/$fileId/_patLessComponents': {
      id: '/files/$fileId/_patLessComponents'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdPatLessComponentsRouteImport
      parentRoute: typeof FilesFileIdRoute
    }
    '/files/$fileId/': {
      id: '/files/$fileId/'
      path: '/'
      fullPath: '/files/$fileId/'
      preLoaderRoute: typeof FilesFileIdIndexImport
      parentRoute: typeof FilesFileIdImport
    }
    '/files/$fileId/_patLessComponents/blocks': {
      id: '/files/$fileId/_patLessComponents/blocks'
      path: '/blocks'
      fullPath: '/files/$fileId/blocks'
      preLoaderRoute: typeof FilesFileIdPatLessComponentsBlocksImport
      parentRoute: typeof FilesFileIdPatLessComponentsRouteImport
    }
    '/files/$fileId/_patLessComponents/layers': {
      id: '/files/$fileId/_patLessComponents/layers'
      path: '/layers'
      fullPath: '/files/$fileId/layers'
      preLoaderRoute: typeof FilesFileIdPatLessComponentsLayersImport
      parentRoute: typeof FilesFileIdPatLessComponentsRouteImport
    }
  }
}

// Create and export the route tree

interface FilesFileIdPatLessComponentsRouteRouteChildren {
  FilesFileIdPatLessComponentsBlocksRoute: typeof FilesFileIdPatLessComponentsBlocksRoute
  FilesFileIdPatLessComponentsLayersRoute: typeof FilesFileIdPatLessComponentsLayersRoute
}

const FilesFileIdPatLessComponentsRouteRouteChildren: FilesFileIdPatLessComponentsRouteRouteChildren =
  {
    FilesFileIdPatLessComponentsBlocksRoute:
      FilesFileIdPatLessComponentsBlocksRoute,
    FilesFileIdPatLessComponentsLayersRoute:
      FilesFileIdPatLessComponentsLayersRoute,
  }

const FilesFileIdPatLessComponentsRouteRouteWithChildren =
  FilesFileIdPatLessComponentsRouteRoute._addFileChildren(
    FilesFileIdPatLessComponentsRouteRouteChildren,
  )

interface FilesFileIdRouteChildren {
  FilesFileIdPatLessComponentsRouteRoute: typeof FilesFileIdPatLessComponentsRouteRouteWithChildren
  FilesFileIdIndexRoute: typeof FilesFileIdIndexRoute
}

const FilesFileIdRouteChildren: FilesFileIdRouteChildren = {
  FilesFileIdPatLessComponentsRouteRoute:
    FilesFileIdPatLessComponentsRouteRouteWithChildren,
  FilesFileIdIndexRoute: FilesFileIdIndexRoute,
}

const FilesFileIdRouteWithChildren = FilesFileIdRoute._addFileChildren(
  FilesFileIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks/$blockId': typeof BlocksBlockIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/layers/$layerId': typeof LayersLayerIdRoute
  '/files': typeof FilesIndexRoute
  '/files/$fileId': typeof FilesFileIdPatLessComponentsRouteRouteWithChildren
  '/files/$fileId/': typeof FilesFileIdIndexRoute
  '/files/$fileId/blocks': typeof FilesFileIdPatLessComponentsBlocksRoute
  '/files/$fileId/layers': typeof FilesFileIdPatLessComponentsLayersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks/$blockId': typeof BlocksBlockIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/layers/$layerId': typeof LayersLayerIdRoute
  '/files': typeof FilesIndexRoute
  '/files/$fileId': typeof FilesFileIdIndexRoute
  '/files/$fileId/blocks': typeof FilesFileIdPatLessComponentsBlocksRoute
  '/files/$fileId/layers': typeof FilesFileIdPatLessComponentsLayersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blocks/$blockId': typeof BlocksBlockIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/layers/$layerId': typeof LayersLayerIdRoute
  '/files/': typeof FilesIndexRoute
  '/files/$fileId': typeof FilesFileIdRouteWithChildren
  '/files/$fileId/_patLessComponents': typeof FilesFileIdPatLessComponentsRouteRouteWithChildren
  '/files/$fileId/': typeof FilesFileIdIndexRoute
  '/files/$fileId/_patLessComponents/blocks': typeof FilesFileIdPatLessComponentsBlocksRoute
  '/files/$fileId/_patLessComponents/layers': typeof FilesFileIdPatLessComponentsLayersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks/$blockId'
    | '/entities/$entityId'
    | '/layers/$layerId'
    | '/files'
    | '/files/$fileId'
    | '/files/$fileId/'
    | '/files/$fileId/blocks'
    | '/files/$fileId/layers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks/$blockId'
    | '/entities/$entityId'
    | '/layers/$layerId'
    | '/files'
    | '/files/$fileId'
    | '/files/$fileId/blocks'
    | '/files/$fileId/layers'
  id:
    | '__root__'
    | '/'
    | '/blocks/$blockId'
    | '/entities/$entityId'
    | '/layers/$layerId'
    | '/files/'
    | '/files/$fileId'
    | '/files/$fileId/_patLessComponents'
    | '/files/$fileId/'
    | '/files/$fileId/_patLessComponents/blocks'
    | '/files/$fileId/_patLessComponents/layers'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksBlockIdRoute: typeof BlocksBlockIdRoute
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  LayersLayerIdRoute: typeof LayersLayerIdRoute
  FilesIndexRoute: typeof FilesIndexRoute
  FilesFileIdRoute: typeof FilesFileIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksBlockIdRoute: BlocksBlockIdRoute,
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  LayersLayerIdRoute: LayersLayerIdRoute,
  FilesIndexRoute: FilesIndexRoute,
  FilesFileIdRoute: FilesFileIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blocks/$blockId",
        "/entities/$entityId",
        "/layers/$layerId",
        "/files/",
        "/files/$fileId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blocks/$blockId": {
      "filePath": "blocks/$blockId.tsx"
    },
    "/entities/$entityId": {
      "filePath": "entities/$entityId.tsx"
    },
    "/layers/$layerId": {
      "filePath": "layers/$layerId.tsx"
    },
    "/files/": {
      "filePath": "files/index.tsx"
    },
    "/files/$fileId": {
      "filePath": "files/$fileId/_patLessComponents",
      "children": [
        "/files/$fileId/_patLessComponents",
        "/files/$fileId/"
      ]
    },
    "/files/$fileId/_patLessComponents": {
      "filePath": "files/$fileId/_patLessComponents/route.tsx",
      "parent": "/files/$fileId",
      "children": [
        "/files/$fileId/_patLessComponents/blocks",
        "/files/$fileId/_patLessComponents/layers"
      ]
    },
    "/files/$fileId/": {
      "filePath": "files/$fileId/index.tsx",
      "parent": "/files/$fileId"
    },
    "/files/$fileId/_patLessComponents/blocks": {
      "filePath": "files/$fileId/_patLessComponents/blocks.tsx",
      "parent": "/files/$fileId/_patLessComponents"
    },
    "/files/$fileId/_patLessComponents/layers": {
      "filePath": "files/$fileId/_patLessComponents/layers.tsx",
      "parent": "/files/$fileId/_patLessComponents"
    }
  }
}
ROUTE_MANIFEST_END */
